//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AshurovRoman_DataUser.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataUserEntities : DbContext
    {
        private static DataUserEntities _context;
        public DataUserEntities()
            : base("name=DataUserEntities")
        {
        }
        
        public static DataUserEntities GetContext()
        {
            if(_context == null)
            {
                _context = new DataUserEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeVxod> TypeVxod { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
